import React from "react"

export interface menu {
  Items?: menu[]
  title?: string
  icon?: JSX.Element
  type?: string
  selected?: boolean
  active?: boolean
  path?: string
  children?: menu[]
  badge?: string
  badgetxt?: string
}



export const MENUITEMS: menu[] = [
  {
    Items: [
      {
        title: "Dashboards",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}dashboard/dashboard01`,
            type: "link",
            active: false,
            selected: false,
            title: "Dashboard 01",
          },
          {
            path: `${import.meta.env.BASE_URL}dashboard/dashboard02`,
            type: "link",
            active: false,
            selected: false,
            title: "Dashboard 02",
          },
          {
            path: `${import.meta.env.BASE_URL}dashboard/dashboard03`,
            type: "link",
            active: false,
            selected: false,
            title: "Dashboard 03",
          },
          {
            path: `${import.meta.env.BASE_URL}dashboard/dashboard04`,
            type: "link",
            active: false,
            selected: false,
            title: "Dashboard 04",
          },
          {
            path: `${import.meta.env.BASE_URL}dashboard/dashboard05`,
            type: "link",
            active: false,
            selected: false,
            title: "Dashboard 05",
          },
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Apps",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Chat",
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/chat/chat`,
                type: "link",
                active: false,
                selected: false,
                title: "Chat",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/chat/chat02`,
                type: "link",
                active: false,
                selected: false,
                title: "Chat 02",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/chat/chat03`,
                type: "link",
                active: false,
                selected: false,
                title: "Chat 03",
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Contact",
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/contact/contactlist`,
                type: "link",
                active: false,
                selected: false,
                title: "Contact list",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/contact/contactlist02`,
                type: "link",
                active: false,
                selected: false,
                title: "Contact list 02",
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "File Manager",
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/filemanager/filemanager`,
                type: "link",
                active: false,
                selected: false,
                title: "File Manager",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/filemanager/filemanager02`,
                type: "link",
                active: false,
                selected: false,
                title: "File Manager 02",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/filemanager/filedetails`,
                type: "link",
                active: false,
                selected: false,
                title: "File Details",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/filemanager/fileattachments`,
                type: "link",
                active: false,
                selected: false,
                title: "File Attachments",
              },
            ],
          },
          
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Todo List",
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/todolist/todolist`,
                type: "link",
                active: false,
                selected: false,
                title: "Todo List",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/todolist/todolist02`,
                type: "link",
                active: false,
                selected: false,
                title: "Todo List 02",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/todolist/todolist03`,
                type: "link",
                active: false,
                selected: false,
                title: "Todo List 03",
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "User List",
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/userlist/userlist01`,
                type: "link",
                active: false,
                selected: false,
                title: "User List 01",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/userlist/userlist02`,
                type: "link",
                active: false,
                selected: false,
                title: "User List 02",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/userlist/userlist03`,
                type: "link",
                active: false,
                selected: false,
                title: "User List 03",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/userlist/userlist04`,
                type: "link",
                active: false,
                selected: false,
                title: "User List 04",
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Maps",
            children: [
              {
                path: `${import.meta.env.BASE_URL}Apps/Maps/SimpleMaps`,
                type: "link",
                active: false,
                selected: false,
                title: "Simple Maps",
              },
              {
                path: `${import.meta.env.BASE_URL}apps/maps/leafletmaps`,
                type: "link",
                active: false,
                selected: false,
                title: "Leaflet Maps",
              },
            ],
          },
          {
            path: `${import.meta.env.BASE_URL}apps/calendar`,
            type: "link",
            active: false,
            selected: false,
            title: "Calendar",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/imagecrop`,
            type: "link",
            active: false,
            selected: false,
            title: "Image Crop",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/pagesessiontimeout`,
            type: "link",
            active: false,
            selected: false,
            title: "Page Sessiontimeout",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/notifications`,
            type: "link",
            active: false,
            selected: false,
            title: "Notifications",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/sweetalerts`,
            type: "link",
            active: false,
            selected: false,
            title: "Sweet Alerts",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/rangeslider`,
            type: "link",
            active: false,
            selected: false,
            title: "Range Slider",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/counters`,
            type: "link",
            active: false,
            selected: false,
            title: "Counters",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/loaders`,
            type: "link",
            active: false,
            selected: false,
            title: "Loaders",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/timeline`,
            type: "link",
            active: false,
            selected: false,
            title: "Time Line",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/rating`,
            type: "link",
            active: false,
            selected: false,
            title: "Rating",
          },
        ],
      }
    ]
  },
  {
    Items: [
      {
        title: "Widgets",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}widgets/widgets`,
            type: "link",
            active: false,
            selected: false,
            title: "Widgets",
          },
          {
            path: `${import.meta.env.BASE_URL}widgets/chartwidgets`,
            type: "link",
            active: false,
            selected: false,
            title: "Chart Widgets",
          },

        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Forms",
        icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}forms/formelements`,
            type: "link",
            active: false,
            selected: false,
            title: "Form Elements",
          },
          {
            path: `${import.meta.env.BASE_URL}forms/advancedforms`,
            type: "link",
            active: false,
            selected: false,
            title: "Advanced Forms",
          },
          {
            path: `${import.meta.env.BASE_URL}forms/formwizard`,
            type: "link",
            active: false,
            selected: false,
            title: "Form Wizard",
          },
          {
            path: `${import.meta.env.BASE_URL}forms/formedit`,
            type: "link",
            active: false,
            selected: false,
            title: "Form Edit",
          },
          {
            path: `${import.meta.env.BASE_URL}forms/formelementsizes`,
            type: "link",
            active: false,
            selected: false,
            title: "Form Element Sizes",
          },
          {
            path: `${import.meta.env.BASE_URL}forms/formtreeview`,
            type: "link",
            active: false,
            selected: false,
            title: "Form Treeview",
          },
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Charts",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21.21 15.89A10 10 0 1 1 8 2.83"></path><path d="M22 12A10 10 0 0 0 12 2v10z"></path></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Apex Charts",
            children: [
              {
                path: `${import.meta.env.BASE_URL}charts/apexcharts/area`,
                type: "link",
                active: false,
                selected: false,
                title: "Area",
              },
              {
                path: `${import.meta.env.BASE_URL}charts/apexcharts/bar`,
                type: "link",
                active: false,
                selected: false,
                title: "Bar",
              },
              {
                path: `${import.meta.env.BASE_URL}charts/apexcharts/column`,
                type: "link",
                active: false,
                selected: false,
                title: "Column",
              },
              {
                path: `${import.meta.env.BASE_URL}charts/apexcharts/line`,
                type: "link",
                active: false,
                selected: false,
                title: "Line",
              },
              {
                path: `${import.meta.env.BASE_URL}charts/apexcharts/mixed`,
                type: "link",
                active: false,
                selected: false,
                title: "Mixed",
              },
            ],
          },
          {
            path: `${import.meta.env.BASE_URL}charts/chartjs`,
            type: "link",
            active: false,
            selected: false,
            title: "Chartjs Charts",
          },
          {
            path: `${import.meta.env.BASE_URL}charts/echart`,
            type: "link",
            active: false,
            selected: false,
            title: "Echart Charts",
          },
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Tables",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}tables/defaulttable`,
            type: "link",
            active: false,
            selected: false,
            title: "Default Table",
          },
          {
            path: `${import.meta.env.BASE_URL}tables/datatable`,
            type: "link",
            active: false,
            selected: false,
            title: "Data Table",
          },
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Elements",
        icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}elements/accordion`,
            type: "link",
            active: false,
            selected: false,
            title: "Accordion",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/alerts`,
            type: "link",
            active: false,
            selected: false,
            title: "Alerts",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/avatars`,
            type: "link",
            active: false,
            selected: false,
            title: "Avatars",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/badges`,
            type: "link",
            active: false,
            selected: false,
            title: "Badges",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/breadcrumb`,
            type: "link",
            active: false,
            selected: false,
            title: "Breadcrumb",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/buttons`,
            type: "link",
            active: false,
            selected: false,
            title: "Buttons",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/cards`,
            type: "link",
            active: false,
            selected: false,
            title: "Cards",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/cardimages`,
            type: "link",
            active: false,
            selected: false,
            title: "Card Images",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/carousel`,
            type: "link",
            active: false,
            selected: false,
            title: "Carousel",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/dropdown`,
            type: "link",
            active: false,
            selected: false,
            title: "Dropdown",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/footers`,
            type: "link",
            active: false,
            selected: false,
            title: "Footers",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/headers`,
            type: "link",
            active: false,
            selected: false,
            title: "Headers",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/list`,
            type: "link",
            active: false,
            selected: false,
            title: "list",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/mediaobject`,
            type: "link",
            active: false,
            selected: false,
            title: "Media Object",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/modal`,
            type: "link",
            active: false,
            selected: false,
            title: "Modal",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/navigation`,
            type: "link",
            active: false,
            selected: false,
            title: "Navigation",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/pagination`,
            type: "link",
            active: false,
            selected: false,
            title: "Pagination",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/panel`,
            type: "link",
            active: false,
            selected: false,
            title: "Panel",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/popover`,
            type: "link",
            active: false,
            selected: false,
            title: "Popover",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/progress`,
            type: "link",
            active: false,
            selected: false,
            title: "Progress",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/tabs`,
            type: "link",
            active: false,
            selected: false,
            title: "Tabs",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/tags`,
            type: "link",
            active: false,
            selected: false,
            title: "Tags",
          },
          {
            path: `${import.meta.env.BASE_URL}elements/tooltips`,
            type: "link",
            active: false,
            selected: false,
            title: "Tooltips",
          },
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Icons",
        icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"></path></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}icons/fontawesome`,
            type: "link",
            active: false,
            selected: false,
            title: "Font Awesome",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/materialdesignicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Material Design Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/simplelineicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Simple Line Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/feathericons`,
            type: "link",
            active: false,
            selected: false,
            title: "Feather Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/ionicicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Ionic Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/flagicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Flag Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/pe7icons`,
            type: "link",
            active: false,
            selected: false,
            title: "Pe7 Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/themifyicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Themify Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/typiconsicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Tyicons Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/weathericons`,
            type: "link",
            active: false,
            selected: false,
            title: "Weather Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/materialicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Material Icons",
          },
          {
            path: `${import.meta.env.BASE_URL}icons/bootstrap5svgicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Bootstrap5 SVG Icons",
          },
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Pages",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Profile",
            children: [
              {
                type: "link",
                active: false,
                selected: false,
                title: "Profile 01",
                path: `${import.meta.env.BASE_URL}pages/profile/profile01`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Profile 02",
                path: `${import.meta.env.BASE_URL}pages/profile/profile02`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Profile 03",
                path: `${import.meta.env.BASE_URL}pages/profile/profile03`,
              },
            ],
          },
          {
            path: `${import.meta.env.BASE_URL}pages/aboutus`,
            type: "link",
            active: false,
            selected: false,
            title: "About Us",
          },
          {
            path: `${import.meta.env.BASE_URL}pages/editprofile`,
            type: "link",
            active: false,
            selected: false,
            title: "Edit Profile",
          },
          {
            path: `${import.meta.env.BASE_URL}pages/settings`,
            type: "link",
            active: false,
            selected: false,
            title: "Settings",
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Email",
            children: [
              {
                type: "link",
                active: false,
                selected: false,
                title: "Email Compose",
                path: `${import.meta.env.BASE_URL}pages/email/emailcompose`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Email Inbox",
                path: `${import.meta.env.BASE_URL}pages/email/emailinbox`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Email Read",
                path: `${import.meta.env.BASE_URL}pages/email/emailread`,
              },
            ],
          },
          {

            type: "sub",
            active: false,
            selected: false,
            title: "Pricing",
            children: [
              {
                type: "link",
                active: false,
                selected: false,
                title: "Pricing 01",
                path: `${import.meta.env.BASE_URL}pages/pricing/pricing01`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "pricing 02",
                path: `${import.meta.env.BASE_URL}pages/pricing/pricing02`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "pricing 03",
                path: `${import.meta.env.BASE_URL}pages/pricing/pricing03`,
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Invoice",
            children: [
              {
                type: "link",
                active: false,
                selected: false,
                title: "Invoice list",
                path: `${import.meta.env.BASE_URL}pages/invoice/invoicelist`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Invoice 01",
                path: `${import.meta.env.BASE_URL}pages/invoice/invoice01`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Invoice 02",
                path: `${import.meta.env.BASE_URL}pages/invoice/invoice02`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Invoice 03",
                path: `${import.meta.env.BASE_URL}pages/invoice/invoice03`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Add Invoice",
                path: `${import.meta.env.BASE_URL}pages/invoice/addinvoice`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Edit Invoice",
                path: `${import.meta.env.BASE_URL}pages/invoice/editinvoice`,
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Blog",
            children: [
              {
                type: "link",
                active: false,
                selected: false,
                title: "Blog 01",
                path: `${import.meta.env.BASE_URL}pages/blog/blog01`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Blog 02",
                path: `${import.meta.env.BASE_URL}pages/blog/blog02`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Blog 03",
                path: `${import.meta.env.BASE_URL}pages/blog/blog03`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Blog Styles",
                path: `${import.meta.env.BASE_URL}pages/blog/blogstyles`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Blog Post",
                path: `${import.meta.env.BASE_URL}pages/blog/blogpost`,
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "E-commerce",
            children: [
              {
                type: "link",
                active: false,
                selected: false,
                title: "Products",
                path: `${import.meta.env.BASE_URL}pages/ecommerce/products`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Product Details",
                path: `${import.meta.env.BASE_URL}pages/ecommerce/productdetails`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Shopping Cart",
                path: `${import.meta.env.BASE_URL}pages/ecommerce/shoppingcart`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Checkout",
                path: `${import.meta.env.BASE_URL}pages/ecommerce/checkout`,
              },
              {
                type: "link",
                active: false,
                selected: false,
                title: "Wishlist",
                path: `${import.meta.env.BASE_URL}pages/ecommerce/wishlist`,
              },
            ],
          },
          {
            path: `${import.meta.env.BASE_URL}pages/gallery`,
            type: "link",
            active: false,
            selected: false,
            title: "Gallery",
          },
          {
            path: `${import.meta.env.BASE_URL}pages/faqs`,
            type: "link",
            active: false,
            selected: false,
            title: "FAQS",
          },
          {
            path: `${import.meta.env.BASE_URL}pages/terms`,
            type: "link",
            active: false,
            selected: false,
            title: "Terms",
          },
          {
            path: `${import.meta.env.BASE_URL}pages/emptypage`,
            type: "link",
            active: false,
            selected: false,
            title: "Empty Page",
          },
          {
            path: `${import.meta.env.BASE_URL}pages/switcher`,
            type: "link",
            active: false,
            selected: false,
            title: "Switcher",
          },
          {
            path: `${import.meta.env.BASE_URL}pages/search`,
            type: "link",
            active: false,
            selected: false,
            title: "Search",
          },
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Submenus",
        icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}#`,
            type: "link",
            active: false,
            selected: false,
            title: "Level-1",
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Level-2",

            children: [
              {
                path: `${import.meta.env.BASE_URL}#`,
                type: "link",
                active: false,
                selected: false,
                title: "Level-2.1",
              },
              {
                path: `${import.meta.env.BASE_URL}#`,
                type: "link",
                active: false,
                selected: false,
                title: "Level-2.2",
              },
              {
                path: `${import.meta.env.BASE_URL}#`,
                type: "link",
                active: false,
                selected: false,
                title: "Level-2.3",
              },

            ],
          },

        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Account",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Login",
            children: [
              {
                path: `${import.meta.env.BASE_URL}account/login/login01`,
                type: "link",
                active: false,
                selected: false,
                title: "Login 01",
              },
              {
                path: `${import.meta.env.BASE_URL}account/login/login02`,
                type: "link",
                active: false,
                selected: false,
                title: "Login 02",
              },
              {
                path: `${import.meta.env.BASE_URL}account/login/login03`,
                type: "link",
                active: false,
                selected: false,
                title: "Login 03",
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Register",
            children: [
              {
                path: `${import.meta.env.BASE_URL}account/register/register01`,
                type: "link",
                active: false,
                selected: false,
                title: "Register 01",
              },
              {
                path: `${import.meta.env.BASE_URL}account/register/register02`,
                type: "link",
                active: false,
                selected: false,
                title: "Register 02",
              },
              {
                path: `${import.meta.env.BASE_URL}account/register/register03`,
                type: "link",
                active: false,
                selected: false,
                title: "Register 03",
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Forget Password",
            children: [
              {
                path: `${import.meta.env.BASE_URL}account/forgetpassword/forgetpassword01`,
                type: "link",
                active: false,
                selected: false,
                title: "Forget Password 01",
              },
              {
                path: `${import.meta.env.BASE_URL}account/forgetpassword/forgetpassword02`,
                type: "link",
                active: false,
                selected: false,
                title: "Forget Password 02",
              },
              {
                path: `${import.meta.env.BASE_URL}account/forgetpassword/forgetpassword03`,
                type: "link",
                active: false,
                selected: false,
                title: "Forget Password 03",
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Reset Password",
            children: [
              {
                path: `${import.meta.env.BASE_URL}account/resetpassword/resetpassword01`,
                type: "link",
                active: false,
                selected: false,
                title: "Reset Password 01",
              },
              {
                path: `${import.meta.env.BASE_URL}account/resetpassword/resetpassword02`,
                type: "link",
                active: false,
                selected: false,
                title: "Reset Password 02",
              },
              {
                path: `${import.meta.env.BASE_URL}account/resetpassword/resetpassword03`,
                type: "link",
                active: false,
                selected: false,
                title: "Reset Password 03",
              },
            ],
          },
          {
            type: "sub",
            active: false,
            selected: false,
            title: "Lock Screen",
            children: [
              {
                path: `${import.meta.env.BASE_URL}account/lockscreen/lockscreen01`,
                type: "link",
                active: false,
                selected: false,
                title: "Lock Screen 01",
              },
              {
                path: `${import.meta.env.BASE_URL}account/lockscreen/lockscreen02`,
                type: "link",
                active: false,
                selected: false,
                title: "Lock Screen 02",
              },
              {
                path: `${import.meta.env.BASE_URL}account/lockscreen/lockscreen03`,
                type: "link",
                active: false,
                selected: false,
                title: "Lock Screen 03",
              },
            ],
          },
          {
            path: `${import.meta.env.BASE_URL}account/underconstruction`,
            type: "link",
            active: false,
            selected: false,
            title: "Under Construction",
          },
          {
            path: `${import.meta.env.BASE_URL}account/comingsoon`,
            type: "link",
            active: false,
            selected: false,
            title: "Coming Soon",
          },
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Error Pages",
        icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="side-menu__icon"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}errorpages/error400`,
            type: "link",
            active: false,
            selected: false,
            title: "400",
          },
          {
            path: `${import.meta.env.BASE_URL}errorpages/error401`,
            type: "link",
            active: false,
            selected: false,
            title: "401",
          },
          {
            path: `${import.meta.env.BASE_URL}errorpages/error403`,
            type: "link",
            active: false,
            selected: false,
            title: "403",
          },
          {
            path: `${import.meta.env.BASE_URL}errorpages/error404`,
            type: "link",
            active: false,
            selected: false,
            title: "404",
          },
          {
            path: `${import.meta.env.BASE_URL}errorpages/error500`,
            type: "link",
            active: false,
            selected: false,
            title: "500",
          },
          {
            path: `${import.meta.env.BASE_URL}errorpages/error503`,
            type: "link",
            active: false,
            selected: false,
            title: "503",
          },
        ],
      },
    ],
  },
  {
    Items: [
      {
        title: "Utilities",
        icon: <svg className="side-menu__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><rect x="9" y="9" width="6" height="6"></rect><line x1="9" y1="1" x2="9" y2="4"></line><line x1="15" y1="1" x2="15" y2="4"></line><line x1="9" y1="20" x2="9" y2="23"></line><line x1="15" y1="20" x2="15" y2="23"></line><line x1="20" y1="9" x2="23" y2="9"></line><line x1="20" y1="14" x2="23" y2="14"></line><line x1="1" y1="9" x2="4" y2="9"></line><line x1="1" y1="14" x2="4" y2="14"></line></svg>,
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}utilities/color`,
            type: "link",
            active: false,
            selected: false,
            title: "Color",
          },
          {
            path: `${import.meta.env.BASE_URL}utilities/flexitems`,
            type: "link",
            active: false,
            selected: false,
            title: "Flex Items",
          },
          {
            path: `${import.meta.env.BASE_URL}utilities/height`,
            type: "link",
            active: false,
            selected: false,
            title: "Height",
          },
          {
            path: `${import.meta.env.BASE_URL}utilities/border`,
            type: "link",
            active: false,
            selected: false,
            title: "Border",
          },
          {
            path: `${import.meta.env.BASE_URL}utilities/display`,
            type: "link",
            active: false,
            selected: false,
            title: "Display",
          },
          {
            path: `${import.meta.env.BASE_URL}utilities/margin`,
            type: "link",
            active: false,
            selected: false,
            title: "Margin",
          },
          {
            path: `${import.meta.env.BASE_URL}utilities/padding`,
            type: "link",
            active: false,
            selected: false,
            title: "Padding",
          },
          {
            path: `${import.meta.env.BASE_URL}utilities/typography`,
            type: "link",
            active: false,
            selected: false,
            title: "Typography",
          },
          {
            path: `${import.meta.env.BASE_URL}utilities/width`,
            type: "link",
            active: false,
            selected: false,
            title: "Width",
          },
        ],
      },
    ],
  },
];
